### ISSUE TITLE
"/loadscene col" throws exception

### ISSUE THREAD

**Issue by rosaqq** [secknv/lekek#53]
```
loading scene - col
initializing serialized scene
scene loaded
java.io.InvalidClassException: net.sknv.engine.SkyBox; local class incompatible: stream classdesc serialVersionUID = 3274102650254189800, local class serialVersionUID = -1980483342522881629
	at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:689)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1903)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1772)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2249)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at net.sknv.engine.Scene.load(Scene.java:81)
	at net.sknv.engine.Scene.<init>(Scene.java:25)
	at net.sknv.game.UltimateKekGame.initScene(UltimateKekGame.java:80)
	at net.sknv.game.UltimateKekGame.processTerminal(UltimateKekGame.java:302)
	at net.sknv.game.UltimateKekGame.lambda$setKeyCallbacks$0(UltimateKekGame.java:241)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at net.sknv.engine.Window.update(Window.java:133)
	at net.sknv.engine.GameEngine.render(GameEngine.java:109)
	at net.sknv.engine.GameEngine.gameLoop(GameEngine.java:66)
	at net.sknv.engine.GameEngine.run(GameEngine.java:29)
	at net.sknv.game.Main.main(Main.java:18)
```

**Comment by rosaqq** [comment]
already fixed with #60
